[package]
name = "tokio-dbus-examples"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.75"
tokio = { version = "1.34.0", features = ["full"] }
tokio-dbus = { path = "../crates/tokio-dbus" }
